module.exports = [
  'Back Squat',
  'Front Squat',
  'Deadlift',
  'press',
  'Push Press',
  'Clean',
  'Power Clean',
  'Clean & Jerk',
  'Push Jerk',
  'Bench Press',
  'Thruster',
  'Row 500m',
  'Row 1,000m',
  'Row 2,000m',
  'Row 5,000m',
  'Row 10,000m',
  'Bike Erg 30 min',
  'Bike Erg 60 min',
  'Bike Erg marathon',
  'Run 5km',
  'Run 10km',
  'Murph',
  'Cindy',
  'Grace',
  'Isabelle'
];
