export const recordList = {
  strength: [
    'Back Squat',
    'Bench Press',
    'Clean',
    'Clean & Jerk',
    'Deadlift',
    'Front Squat',
    'Press',
    'Push Press',
    'Power Clean',
    'Push Jerk',
    'Snatch',
    'Thruster',
  ],
  endurance: [
    '10 min Air Bike',
    '30 min Air Bike',
    'Bike Erg 30 min',
    'Bike Erg 60 min',
    'Bike Erg marathon',
    'Row 500m',
    'Row 1,000m',
    'Row 2,000m',
    'Row 5,000m',
    'Row 10,000m',
    'Run 5km',
    'Run 10km',
  ],
  wod: [
    'Angie',
    'Cindy',
    'Diane',
    'DT',
    'Fight Gone Badge',
    'Filthy Fifty',
    'Fran',
    'Grace',
    'Helen',
    'Isabelle',
    'Jackie',
    'Linda',
    'Murph',
  ]
};
