# Generated by Django 3.2 on 2021-05-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20210501_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='body',
            new_name='workout_body',
        ),
    ]
