# Generated by Django 3.2 on 2021-05-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_rename_body_workout_workout_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.TimeField(default='12:00'),
        ),
    ]
