# Generated by Django 3.2.13 on 2022-06-24 12:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0004_alter_workout_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workout',
            unique_together={('author', 'date')},
        ),
    ]
