services:
    server:
        build: .
        container_name: workout-tracker-server
        restart: always
        command: "${SERVER_RUN_COMMAND}"
        volumes:
            - .:/server_src
        ports:
            - 8000:8000
        depends_on:
            - db

    db:
        image: postgres:11
        container_name: workout-tracker-db
        restart: always
        ports:
            - "5432:5432"
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
            - "POSTGRES_DB=${POSTGRES_DATABASE_NAME}"
            - "POSTGRES_USER=${POSTGRES_DATABASE_USER}"
            - "POSTGRES_PASSWORD=${POSTGRES_DATABASE_PASSWORD}"
        volumes:
            - db:/var/lib/postgresql/data
volumes:
    db:
        driver: local
