# Generated by Django 3.2 on 2021-05-03 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('event', models.CharField(choices=[('back_squat', 'Back Squat'), ('front_squat', 'Front Squat'), ('deadlift', 'Deadlift'), ('press', 'press'), ('push_press', 'Push Press'), ('clean', 'Clean'), ('power_clean', 'Power Clean'), ('clean_and_jerk', 'Clean & Jerk'), ('push_jerk', 'Push Jerk'), ('bench_press', 'Bench Press'), ('thruster', 'Thruster'), ('row_500', 'Row 500m'), ('row_1000', 'Row 1,000m'), ('row_2000', 'Row 2,000m'), ('row_5000', 'Row 5,000m'), ('row_10000', 'Row 10,000m'), ('bike_erg_30', 'Bike Erg 30 min'), ('bike_erg_60', 'Bike Erg 60 min'), ('bike_erg_marathon', 'Bike Erg marathon'), ('run_5k', 'Run 5km'), ('run_10k', 'Run 10km'), ('murph', 'Murph'), ('cindy', 'Cindy'), ('grace', 'Grace'), ('isabelle', 'Isabelle')], default='back_squat', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
