# Generated by Django 3.2 on 2021-05-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='score',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
