# Generated by Django 3.2 on 2021-05-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_record_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='event',
            field=models.CharField(default='', max_length=100),
        ),
    ]
