# Generated by Django 3.2 on 2021-05-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_record_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='type',
            field=models.CharField(default='strength', max_length=200),
        ),
    ]
