# Generated by Django 3.2.13 on 2022-06-24 12:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0005_record_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('author', 'date', 'event')},
        ),
    ]
