name: Flake8 + Python Tests + Deploy Backend

on:
    push:
        branches:
            - main
        paths:
            - "server/**"

jobs:
    test:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:10
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Set Up Python 3.9
              uses: actions/setup-python@v3
              with:
                  python-version: "3.9"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r server/requirements.txt
            - name: Run python tests
              env:
                  DJANGO_TEST: "True"
                  DJANGO_DEVELOPMENT: "True"
              run: python3 manage.py test --no-input
              working-directory: server
            - name: Run Flake8
              uses: py-actions/flake8@v2
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: ssh into droplet & deploy server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: |
                      cd workout-tracker/server
                      git pull origin main
                      docker compose stop
                      docker compose up -d --build web
