name: ESLint + Jest + Deploy Frontend

on:
    push:
        branches:
            - main
        paths:
            - "client/build/**"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install modules
              run: npm install
              working-directory: client
            - name: Run ESLint
              run: npm run lint
              working-directory: client
            - name: Run Jest tests
              run: npm run test
              working-directory: client
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: ssh into droplet & deploy static files
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: |
                      cd workout-tracker
                      git pull origin main
                      bash script/update-static-files.sh
