name: ESLint

on: 
  push:
    paths:
    - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
      working-directory: client
    - name: Run ESLint
      run: yarn lint
      working-directory: client