name: Flake8

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set Up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Run Flake8
      uses: py-actions/flake8@v2
      working-directory: server

