name: Jest

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Navigate to frontend code
      run: cd client
    - name: Install modules
      run: yarn
    - name: Run Jest tests
      run: yarn test