name: Python Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set Up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      env:
        DJANGO_DEVELOPMENT: 'True'
        DJANGO_SECRETE_KEY: 'django-insecure-fdrao0y^p+6eq5+hk^$e8nlsnf*a9zyl6%z#!u+fsak)=uh#be'
        SERVER_RUN_COMMAND: 'sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"'
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt
        pip install docker-compose
    - name: Run server
      run: docker-compose up -d --build web
      working-directory: server
    - name: Run tests
      run: docker-compose exec web python manage.py test
