name: Python Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    # services:
    #   postgres:
    #     image: postgres:10
    #     env:
    #       POSTGRES_HOST_AUTH_METHOD: trust
    #       POSTGRES_DB: workout
    #       POSTGRES_USER: flavoie
    #       POSTGRES_PASSWORD: testing
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     ports:
    #       - 5432:5432
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set Up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt
        pip install docker-compose
    - name: Run server
      env:
        SERVER_RUN_COMMAND: 'sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"'
      run: docker-compose up -d --build web
      working-directory: server
    - name: Run tests
      run: python manage.py test
      working-directory: server
